version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build:
      context: .
    container_name: blog-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - DISABLE_REDIS=false
      - LOG_SUMMARY_TRAINING=true
    command: sh -c "npm install && npm run dev"
